--ptBR
-- Guild Slacker AutoGenerated Localization if you want to help translate 
-- Go to https://www.curseforge.com/wow/addons/guild-slacker/localization 

local L = LibStub("AceLocale-3.0"):NewLocale("GuildSlacker", "ptBR") 
if not L then return end
--@localization(locale="ptBR", format="lua_additive_table",handle-unlocalized="english")@


